// Synced from obsidian-boiler-template/tooling/shared/eslint.base.js. Do not edit this file directly.
import { globalIgnores } from 'eslint/config'
import obsidianmd from 'eslint-plugin-obsidianmd'
import globals from 'globals'
import tseslint from 'typescript-eslint'

// eslint-disable-next-line @typescript-eslint/no-deprecated -- defineConfig doesn't flatten obsidianmd array spread
export const baseConfig = tseslint.config(
	// Enable type-checked rules.
	// projectService discovers tsconfig.json in tsconfigRootDir (plugin root after sync).
	// allowDefaultProject covers config files and test files not included in tsconfig.
	{
		languageOptions: {
			// Obsidian runs in Electron browser context — globals.browser is correct for src/.
			// globals.node is added in the test-file override below for Vitest.
			globals: { ...globals.browser },
			parserOptions: {
				projectService: {
					// allowDefaultProject handles files not covered by tsconfig.json.
					// Cannot use '**' globs — add test files to tsconfig.json include instead.
					allowDefaultProject: [
						'*.config.js',
						'*.config.ts',
						'*.config.mts',
						'*.config.mjs',
						'*.mjs',
						'scripts/*.mjs',
						'tooling/shared/*.mjs',
						'eslint.base.js',
						'tooling/shared/eslint.base.js',
						'manifest.json',
					],
				},
				tsconfigRootDir: import.meta.dirname,
				extraFileExtensions: ['.json'],
			},
		},
	},
	// obsidianmd.configs.recommended includes:
	//   tseslint.configs.recommendedTypeChecked for .ts files
	//   → @typescript-eslint/no-floating-promises, require-await,
	//     no-unnecessary-type-assertion, no-base-to-string, no-explicit-any
	//   no-console: ["error", { allow: ["warn", "error", "debug"] }]
	//   All obsidianmd plugin rules (sentence-case, command-id, hardcoded-config-path, etc.)
	...obsidianmd.configs.recommended,
	// Disable depend/ban-dependencies — too aggressive for the plugin ecosystem
	// (flags legitimate devDeps like lint-staged, builtin-modules).
	{
		rules: {
			'depend/ban-dependencies': 'off',
		},
	},
	// Layer enforcement: domain/, types/, utils/ must not import from obsidian.
	{
		files: ['src/domain/**/*.ts', 'src/types/**/*.ts', 'src/utils/**/*.ts'],
		ignores: ['**/*.d.ts'],
		rules: {
			'no-restricted-imports': ['error', {
				patterns: [{
					group: ['obsidian', 'obsidian/*'],
					message: 'domain/, types/, and utils/ layers must not import from obsidian. Move this code to ui/ or inject the dependency.',
				}],
			}],
		},
	},
	// Worker files: run in Web Worker / Node-like context, need node globals (Buffer, process).
	{
		files: ['worker/**/*.ts'],
		languageOptions: {
			globals: { ...globals.node },
		},
	},
	// Config files: legitimately import Node.js built-in modules.
	{
		files: ['*.config.ts', '*.config.mts', '*.config.js', '*.config.mjs'],
		rules: {
			'import/no-nodejs-modules': 'off',
		},
	},
	// Script files (.mjs): run in Node.js, need node globals.
	{
		files: ['scripts/**/*.mjs', 'tooling/**/*.mjs', '*.mjs'],
		languageOptions: {
			globals: { ...globals.node },
		},
		rules: {
			'import/no-nodejs-modules': 'off',
		},
	},
	// Test files: relax rules that don't apply to test code.
	{
		files: ['test/**/*.ts', '__tests__/**/*.ts'],
		languageOptions: {
			// Vitest runs in Node.js — test files need node globals (process, Buffer, etc.).
			globals: { ...globals.node },
		},
		rules: {
			'@typescript-eslint/no-explicit-any': 'off',
			'@typescript-eslint/no-unsafe-assignment': 'off',
			'@typescript-eslint/no-unsafe-argument': 'off',
			'@typescript-eslint/no-unsafe-member-access': 'off',
			'@typescript-eslint/no-unsafe-call': 'off',
			'@typescript-eslint/no-unsafe-return': 'off',
			// Unbound method references are common in test assertions (vi.spyOn, expect).
			'@typescript-eslint/unbound-method': 'off',
			// Test files use hardcoded paths intentionally for test fixtures.
			'obsidianmd/hardcoded-config-path': 'off',
			// Test files legitimately import Node.js built-in modules.
			'import/no-nodejs-modules': 'off',
		},
	},
	globalIgnores(['main.js', 'dist/', 'node_modules/']),
)
