// Synced from obsidian-boiler-template/tooling/shared/eslint.base.js. Do not edit this file directly.
import eslint from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export const baseConfig = tseslint.config(
	eslint.configs.recommended,
	{
		files: ['**/*.ts'],
		extends: [...tseslint.configs.recommended],
		languageOptions: {
			globals: { ...globals.node },
		},
		rules: {
			'@typescript-eslint/no-unused-vars': ['error', { args: 'none' }],
			'@typescript-eslint/ban-ts-comment': 'off',
			'@typescript-eslint/no-empty-function': 'off',
			'no-prototype-builtins': 'off',
		},
	},
	{
		files: ['src/**/*.ts'],
		rules: {
			'no-console': 'error',
		},
	},
	{
		files: ['src/domain/**/*.ts', 'src/types/**/*.ts', 'src/utils/**/*.ts'],
		ignores: ['**/*.d.ts'],
		rules: {
			'no-restricted-imports': ['error', {
				patterns: [{
					group: ['obsidian', 'obsidian/*'],
					message: 'domain/, types/, and utils/ layers must not import from obsidian. Move this code to ui/ or inject the dependency.',
				}],
			}],
		},
	},
	{
		files: ['scripts/**/*.{js,mjs}', 'tooling/**/*.{js,mjs}', 'esbuild.config.mjs', 'version-bump.mjs'],
		languageOptions: {
			ecmaVersion: 'latest',
			sourceType: 'module',
			globals: { ...globals.node },
		},
	},
	{
		files: ['test/**/*.ts'],
		rules: {
			'@typescript-eslint/no-explicit-any': 'off',
		},
	},
	{ ignores: ['main.js', 'dist/', 'node_modules/'] },
)
