// Synced from obsidian-boiler-template/tooling/shared/src-shared/plugin-logger.ts. Do not edit this file directly.
import { Notice } from 'obsidian';

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

export class PluginLogger {
	constructor(
		private readonly prefix: string,
		private readonly isDebug: () => boolean = () => false,
	) {}

	debug(message: string, data?: Record<string, unknown>): void {
		if (!this.isDebug()) return;
		// eslint-disable-next-line no-console
		console.debug(this.format('debug', message, data));
	}

	info(message: string, data?: Record<string, unknown>): void {
		// eslint-disable-next-line no-console
		console.info(this.format('info', message, data));
	}

	warn(message: string, data?: Record<string, unknown>): void {
		// eslint-disable-next-line no-console
		console.warn(this.format('warn', message, data));
	}

	error(message: string, error?: unknown): void {
		let suffix = '';
		if (error instanceof Error) {
			suffix = ` | ${error.message}`;
		} else if (error) {
			suffix = ` | ${String(error)}`;
		}
		// eslint-disable-next-line no-console
		console.error(`[${this.prefix}] error | ${message}${suffix}`);
	}

	noticeError(message: string, error?: unknown): void {
		this.error(message, error);
		new Notice(`[${this.prefix}] ${message}`);
	}

	private format(level: LogLevel, message: string, data?: Record<string, unknown>): string {
		const pairs = data
			? ` | ${Object.entries(data).map(([k, v]) => `${k}=${JSON.stringify(v)}`).join(' ')}`
			: '';
		return `[${this.prefix}] ${level.padEnd(5)} | ${message}${pairs}`;
	}
}
