#!/usr/bin/env node
// Synced from obsidian-boiler-template/tooling/shared/release.mjs. Do not edit this file directly.

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';

const RELEASE_LEVELS = new Set(['patch', 'minor', 'major']);

function getPnpmCommand() {
  return process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm';
}

function run(command, args) {
  const result = spawnSync(command, args, { stdio: 'inherit' });
  if (result.error) {
    console.error(`Failed to run ${command}: ${result.error.message}`);
    process.exit(1);
  }
  if ((result.status ?? 0) !== 0) {
    process.exit(result.status ?? 1);
  }
}

const level = process.argv[2];
if (!RELEASE_LEVELS.has(level)) {
  console.error(`Usage: node scripts/release.mjs <patch|minor|major>`);
  process.exit(1);
}

const pnpm = getPnpmCommand();
if (fs.existsSync('tooling/sync/index.mjs')) {
  run(pnpm, ['sync:check']);
}
run(pnpm, ['run', 'ci']);
run(pnpm, ['version', level]);
