name: Release plugin

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  PLUGIN_NAME: metadata-auto-classifier

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            main.js
            manifest.json
            styles.css
            versions.json
